version: '2'

services:
    rest-api:
        image: nginx
        ports:
            - 8480:80
        volumes:
            - .:/var/www/html/
            - ./docker/rest-api/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    websocket-server:
        container_name: scratch-robot-ws
        build: docker/php-fpm
        command: php bin/websocket-server
        env_file: .env
        ports:
            - 8482:8482
        volumes:
            - .:/var/www/html/

    php-fpm:
        container_name: scratch-robot-php
        build: docker/php-fpm
        env_file: .env
        volumes:
            - .:/var/www/html/
        links:
            - websocket-server
